apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devenv-manager
  labels:
    app.kubernetes.io/name: devenv-manager
    app.kubernetes.io/component: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devenv-manager
subjects:
  - kind: ServiceAccount
    name: devenv-manager
    namespace: devenv
