apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devenv

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: devenv

images:
  - name: ghcr.io/walkerlab/devenv-manager
    newTag: latest

configMapGenerator: []
secretGenerator: []
